In [1]:
import numpy as np

In [2]:
#Single dimensional Array
a=np.array([1,2,3])
print(a)



[1 2 3]


In [3]:
#Multi Dimensional array
a=np.array([(1,2,3),(4,5,6)])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.shape)


[[1 2 3]
 [4 5 6]]
2
4
6
(2, 3)


In [4]:
#Reshape array
a=a.reshape(3,2)
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [5]:
a=np.array([(1,2,3),(4,5,6)])
#Indexing arrays
print(a[0,2])
print(a[0:,2])
print(a[0:2,1])


3
[3 6]
[2 5]


In [6]:
#Creating array with equally spaced elements
a=np.linspace(1,3,10)
print(a)


[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [7]:
#Array operations
print(a.min())
print(a.max())
print(a.sum())


1.0
3.0
20.0


In [8]:

#Row-wise operations
print(a.sum(axis=0))


20.0


In [9]:
#Array Math functions
print(np.sqrt(a))
print(np.std(a))
a= np.array([1,2,3])
print(np.log(a))
a= np.array([1,2,3])
print(np.log10(a))


[1.         1.1055416  1.20185043 1.29099445 1.37436854 1.45296631
 1.52752523 1.59861051 1.66666667 1.73205081]
0.6382847385042253
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


In [10]:
#Between Array Operations
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

#Stacking the arrays
print(np.vstack((x,y)))
print(np.hstack((x,y)))

# convert one numpy array into a single column
print(x.ravel())


[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
[1 2 3 3 4 5]


In [12]:
import pandas as pd
import numpy as np

#Single dimensional Array
a=np.array([1,2,3])
print(a)



[1 2 3]


In [13]:
#Multi Dimensional array
a=np.array([(1,2,3),(4,5,6)])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.shape)

#Reshape array
a=a.reshape(3,2)
print(a)


a=np.array([(1,2,3),(4,5,6)])
#Indexing arrays
print(a[0,2])
print(a[0:,2])
print(a[0:2,1])



[[1 2 3]
 [4 5 6]]
2
4
6
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
3
[3 6]
[2 5]


In [14]:
#Creating array with equally spaced elements
a=np.linspace(1,3,10)
print(a)

#Array operations
print(a.min())
print(a.max())
print(a.sum())

#Row-wise operations
print(a.sum(axis=0))


[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]
1.0
3.0
20.0
20.0


In [15]:
#Array Math functions
print(np.sqrt(a))
print(np.std(a))
a= np.array([1,2,3])
print(np.log(a))
a= np.array([1,2,3])
print(np.log10(a))

#Between Array Operations
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)
print(x-y)
print(x*y)
print(x/y)



[1.         1.1055416  1.20185043 1.29099445 1.37436854 1.45296631
 1.52752523 1.59861051 1.66666667 1.73205081]
0.6382847385042253
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#Stacking the arrays
print(np.vstack((x,y)))
print(np.hstack((x,y)))



[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [17]:
# convert one numpy array into a single column
print(x.ravel())

[1 2 3 3 4 5]


In [19]:
import pandas as pd

#Read CSV File using pandas functions
data = pd.read_csv('C:\\Users\\admin\\Downloads\\python\\python basis\\basics class1\\example.csv')
#Convert into numpy arrays
dat_np = data.values


In [21]:
import os
#Read CSV using recfromcsv
from numpy import genfromtxt
my_data = genfromtxt('example.csv', delimiter=',')
print(type(my_data))


OSError: example.csv not found.

In [ ]:
#Read from csv using loadtxt method (without columns)
variable = np.loadtxt('example.csv', delimiter=',')

#Save file as csv
import csv

f = open ( 'data.csv' , 'w', newline='' )

with f:
    writer = csv.writer(f)
    writer.writerows(my_data)






#Read CSV using recfromcsv
from numpy import genfromtxt
my_data = genfromtxt('example.csv', delimiter=',')
print(type(my_data))

#Read from csv using loadtxt method (without columns)
variable = np.loadtxt('example.csv', delimiter=',')

#Save file as csv
import csv

f = open ( 'data.csv' , 'w', newline='' )

with f:
    writer = csv.writer(f)
    writer.writerows(my_data)




In [ ]:

#Read CSV File using pandas functions
data = pd.read_csv('C:\\Users\\admin\\Downloads\\python\\python basis\\basics class1\\example.csv')
#Convert into numpy arrays
dat_np = data.values

In [ ]:

#Read CSV using recfromcsv
from numpy import genfromtxt
my_data = genfromtxt('example.csv', delimiter=',')
print(type(my_data))


In [ ]:
#Read from csv using loadtxt method (without columns)
variable = np.loadtxt('example.csv', delimiter=',')

#Save file as csv
import csv

f = open ( 'data.csv' , 'w', newline='' )

with f:
    writer = csv.writer(f)
    writer.writerows(my_data)

